### ISSUE TITLE
module missing, paths mixed up

### ISSUE THREAD

**Issue by pachacamac** [ShadityZ/Vitrix#23]
`venvctl` should be in requirements. But even after that the paths are kind of warbled around and the only way I got it to run was to go inside the linux build, activate the virtual env, install ursina, create the '.unbuilt' file and run singleplayer.py directly.

![Screenshot from 2022-04-15 14-25-02](https://user-images.githubusercontent.com/543577/163570397-c4736068-199e-4527-a998-e18309e9c49c.png)

and only way to quit seems to be alt+f4.

**Comment by ShadityZ** [comment]
If you read the [Official Vitrix Documentation](https://github.com/ShadityZ/Vitrix/blob/docs-development/docs/mainpage.md), you will find that you can press```tab``` to open a pause menu,which after you can close the window with the mouse. Soon I am also making a commit for windows to fix issue #20, that will also add a quit button to the menu as well.

**Comment by ShadityZ** [comment]
Maybe tag as documentation?

**Comment by ShadityZ** [comment]
The issue with the paths is detailed in issue #20. It was also reportedin issue #22. Commit for fix is coming soon, but thanks for the work around until then!

**Comment by pachacamac** [comment]
Ah gotcha good to know :) for user experience I would suggest mapping the `tab` function to `esc` as well since most people are used to this.

**Comment by ShadityZ** [comment]
Yes, I believe that is a good idea, I might change that and map tab to a list the players on the server.

**Comment by ShadityZ** [comment]
Just followed your suggestion and mapped the pause function to the escape key as well, so now ```tab``` and ```esc``` do the same thing.

**Comment by ShadityZ** [comment]
Any updates on this, otherwise I will close it.
