### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by Chateauvisionn** [ShadityZ/Vitrix#31]
Things to remove so the game is not too big (Windows):

vitrix/python/Lib/\__pycache__/
vitrix/python/Lib/email/
vitrix/python/Lib/logging/\__pycache__/ (and basically every \__pycache__ folder)
vitrix/python/Lib/lib2to3/
vitrix/python/Doc/
vitrix/python/Tools/demo/
vitrix/python/Scripts/egg2maya*.exe
vitrix/python/Scripts/maya2egg*.exe
vitrix/python/Scripts/mayacopy*.exe
vitrix/python/Lib/site-packages/\__pycache__/

When you remove all of these, the game is ~253 mb big

I'm gonna add more later

**Comment by ShadityZ** [comment]
Okay. I'll look into it, have you tried it, because I think it may break a few python components

**Comment by Chateauvisionn** [comment]
> Okay. I'll look into it, have you tried it, because I think it may break a few python components

I removed things that aren't used

**Comment by ShadityZ** [comment]
Cool. Should I close the issue now?
