### ISSUE TITLE
Update to python 3.10 in next release

### ISSUE THREAD

**Issue by Chateauvisionn** [ShadityZ/Vitrix#40]
Update to python 3.10 in next pre-built release.

So we can use ```match: case``` instead of ```if: elif: else``` and improve game performance

**Comment by ShadityZ** [comment]
Yes, many elif statements do seem to have been making the game heavier over the last few days. Maybe linked to #31?

**Comment by ShadityZ** [comment]
The problem with this is that it comes with the python bundle for building on windows. At the moment it is really close to 100MB, then we have to push to github LFS, which is considerbably slower and smaller. So for that we might have to use a different archiving format for the bundled python.

**Comment by Chateauvisionn** [comment]
I think i can close this
