### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by Chateauvisionn** [ShadityZ/Vitrix#46]
Add more settings and read/write user/settings.json

**Comment by ShadityZ** [comment]
Chateauvisonn got a little stuck so I've helped him out, and just pushed the code for the ability to write to the json file, but I'm going to work on my part soon on a settings menu in-game on the pause screen.

**Comment by ShadityZ** [comment]
Just implemented the ability to turn your shadows on and off. Also fixed the problem with the ```DirectionalLight()``` instance not liking having shaders disabled, so I made them only instance when shaders are on
